[features]
seeds = false
[programs.localnet]
cryptolotto = "BPMCwnBCkGPtPS2uxvbMVdusZ7gopPDGybnLkaTHMSYR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/alexandremignon/.config/solana/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
